# Generated by Django 4.1 on 2022-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('sobrenome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nasc', models.DateField()),
                ('viela_coin', models.IntegerField(default=30, null=True)),
            ],
        ),
    ]
